server:
  port: 8081
  servlet:
    context-path: /service1-spring

soap:
  wsdl-url: http://localhost:8180/service1-soap/Service1SoapService?wsdl
  namespace: http://soap.service1.lab4.soa.com/
  service-name: Service1SoapService
