spring:
  application:
    name: service1
  datasource:
    url: jdbc:postgresql://localhost:5432/soa
    username: postgres
    password: ltwX,9164
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        scheme: https
        health-check-path: /service1-spring/actuator/health
        health-check-interval: 10s
        health-check-tls-skip-verify: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}

server:
  port: 8443
  servlet:
    context-path: /service1-spring
  ssl:
    enabled: true
    key-store: file:/home/onexpert/soa/keystore.jks
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: myalias

management:
  endpoints:
    web:
      exposure:
        include: health,info
